
included:
  - CotEditor/Sources

opt_in_rules:
  - attributes
  - closure_spacing
  - explicit_init
  - file_header
  - first_where
  - operator_usage_whitespace
  - private_outlet
  - redundant_nil_coalescing
  - valid_docs

disabled_rules:
  - force_cast
  - nesting
  - opening_brace
  - trailing_comma
  - unused_closure_parameter
  
  - force_try
  - variable_name

trailing_whitespace:
  ignores_empty_lines: true

attributes:
  always_on_same_line: ["@IBAction", "@objc"]

vertical_whitespace:
  max_empty_lines: 4

file_length:
  warning: 1500
  error: 3000

line_length:
  warning: 1000
  error: 2000

type_body_length:
  warning: 600
  error: 1000

function_body_length:
  warning: 150
  error: 300

cyclomatic_complexity:
  warning: 25
  error: 50

large_tuple:
  warning: 3
  error: 6
