# ref. http://docs.travis-ci.com/user/languages/objective-c/

language: objective-c
osx_image: xcode8
xcode_workspace: CotEditor.xcworkspace
xcode_scheme: CotEditor
before_install:
  - carthage update --platform OSX
script: xcodebuild -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "$TRAVIS_XCODE_SCHEME" clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

# enable container-based infrastructure
sudo: false
