language: swift
osx_image: xcode10.2

script:
  set -o pipefail &&
  travis_retry
  xcodebuild build
  -workspace CotEditor.xcworkspace
  -scheme CotEditor
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO
  | xcpretty
