name: CI

on: [push, pull_request]

jobs:
  Test:
    runs-on: macOS-latest

    steps:
    - name: Show environments
      run: |
        xcodebuild -version
        swift --version
    - uses: actions/checkout@v1
    - name: Checkout submodules
      run: git submodule update --init
    - name: Lint Swift
      run: |
        brew install swiftlint
        swiftlint
    - name: Unit Test
      run: |
        set -o pipefail
        xcodebuild test -workspace CotEditor.xcworkspace -scheme CotEditor CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
