name: Test

on: [push, pull_request]

jobs:
  macOS:
    runs-on: macos-14

    steps:
    - name: Show environments
      run: |
        sw_vers
        xcodebuild -version
        swift --version
    - uses: actions/checkout@v1
    - name: Checkout submodules
      run: |
        git submodule update --init
    - name: Lint Swift
      run: |
        if [[ ! -f "/usr/local/bin/swiftlint" ]]; then
            brew install swiftlint
        fi
        swiftlint
    - name: Unit Test
      env:
        DEVELOPER_DIR: /Applications/Xcode_16.0-beta.app
      run: |
        set -o pipefail
        xcodebuild test -project CotEditor.xcodeproj -scheme CotEditor CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
    - name: Unit Test for SyntaxMap
      run: |
        cd SyntaxMap
        swift build
        swift test 2>&1 | xcpretty -c
