name: Test

on: [push, pull_request]

jobs:
  macOS:
    runs-on: macos-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.0.app

    steps:
    - name: Show environments
      run: |
        xcodebuild -version
        swift --version
    - uses: actions/checkout@v4
    - name: Checkout submodules
      run: |
        git submodule update --init
    - name: Unit Test for EditorKit
      run: |
        swift test --package-path Packages/EditorKit --enable-swift-testing
    - name: Unit Test for SyntaxMap
      run: |
        swift test --package-path Packages/SyntaxMap --enable-swift-testing
    - name: Unit Test for CotEditor
      run: |
        xcodebuild test -project CotEditor.xcodeproj -scheme CotEditor CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -skipPackagePluginValidation
